--____ABA GERAL_____
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='ATIVA_FECHAR_ODBC') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='1' WHERE COD_PARAMETRO='ATIVA_FECHAR_ODBC';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='ATIVA_XML_BD') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='2' WHERE COD_PARAMETRO='ATIVA_XML_BD';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='BASE_HOMOLOGACAO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(ishom)' WHERE COD_PARAMETRO='BASE_HOMOLOGACAO';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='LEITURA_DOCUMENTO_SAIDA') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(armazxml)' WHERE COD_PARAMETRO='LEITURA_DOCUMENTO_SAIDA';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='PROCESSA_NFSE') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(processnfse)' WHERE COD_PARAMETRO='PROCESSA_NFSE';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='VERSAO_RECEIVER') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(version)' WHERE COD_PARAMETRO='VERSAO_RECEIVER';END;
GO
--____ABA DE SERVICOS_____
IF ('$(ishom)' = '1') 
	BEGIN 
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='CAIXA_EMAIL_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeEmail$(displayhom)' WHERE COD_PARAMETRO='CAIXA_EMAIL_SERVICO'; END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='IMPORTADOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeImport$(displayhom)' WHERE COD_PARAMETRO='IMPORTADOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='VERIFICADOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeVerify$(displayhom)' WHERE COD_PARAMETRO='VERIFICADOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='NFE_CONSULTOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeNfeUtil$(displayhom)' WHERE COD_PARAMETRO='NFE_CONSULTOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='NFSE_CONSULTOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeNfse$(displayhom)' WHERE COD_PARAMETRO='NFSE_CONSULTOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='FONTE_LOG_WINDOWS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='Governanca$(displayhom)' WHERE COD_PARAMETRO='FONTE_LOG_WINDOWS';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='SITE_RECEIVER') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='Governanca$(displayhom)' WHERE COD_PARAMETRO='SITE_RECEIVER';END;
	END;
ELSE 
	BEGIN 
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='CAIXA_EMAIL_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeEmail' WHERE COD_PARAMETRO='CAIXA_EMAIL_SERVICO'; END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='IMPORTADOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeImport' WHERE COD_PARAMETRO='IMPORTADOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='VERIFICADOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeVerify' WHERE COD_PARAMETRO='VERIFICADOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='NFE_CONSULTOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeNfeUtil' WHERE COD_PARAMETRO='NFE_CONSULTOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='NFSE_CONSULTOR_SERVICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='GovDFeNfse' WHERE COD_PARAMETRO='NFSE_CONSULTOR_SERVICO';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='FONTE_LOG_WINDOWS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='Governanca' WHERE COD_PARAMETRO='FONTE_LOG_WINDOWS';END;
		IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='SITE_RECEIVER') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='Governanca' WHERE COD_PARAMETRO='SITE_RECEIVER';END;
	END;
GO
--______ABA AUDITORIA______
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='ATIVA_LOG_BD') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='2' WHERE COD_PARAMETRO='ATIVA_LOG_BD';END;
GO
--______ABA DIRETORIOS______
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_BASE_DOC') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)' WHERE COD_PARAMETRO='DIR_BASE_DOC';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_IMP_REGRAS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\Importacao\Regras' WHERE COD_PARAMETRO='DIR_IMP_REGRAS';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_IMPORTACAO_DOCTO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\Importacao\DocumentosXML' WHERE COD_PARAMETRO='DIR_IMPORTACAO_DOCTO';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_IMPORTACAO_PROCEDA') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\Importacao\DocumentosPROCEDA' WHERE COD_PARAMETRO='DIR_IMPORTACAO_PROCEDA';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_PACOTE') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\Atualizacao' WHERE COD_PARAMETRO='DIR_PACOTE';END;
GO
--______ABA FTS______
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='EXTENSOES_WS_FTS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='.pdf;.eml' WHERE COD_PARAMETRO='EXTENSOES_WS_FTS';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='BLOCK_LIST_AUTOMATICO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='1' WHERE COD_PARAMETRO='BLOCK_LIST_AUTOMATICO';END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='NFSE_DIR_FTS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\FTS\Enviados' WHERE COD_PARAMETRO='NFSE_DIR_FTS';END;
IF ('$(emailfts)' <> '') BEGIN IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='REMETENTE_FTS') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(emailfts)' WHERE COD_PARAMETRO='REMETENTE_FTS';END;END;
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='DIR_FTS_ARMAZENAMENTO') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='$(defaultdir)\FTS\Armazenados' WHERE COD_PARAMETRO='DIR_FTS_ARMAZENAMENTO';END;
GO
--______ABA DASHBOARD______
IF EXISTS(SELECT ta.* FROM TDFE_PARAMETRO_APLICACAO ta  WHERE ta.COD_PARAMETRO='HABILITA_ATUALIZA_DASHBOARD') BEGIN UPDATE TDFE_PARAMETRO_APLICACAO SET DES_VALOR='1' WHERE COD_PARAMETRO='HABILITA_ATUALIZA_DASHBOARD';END;
GO
